name: PR Agent
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_API_BASE: https://rjvke3q.9router.com/v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG__AI__MODEL: fast-model
          CONFIG__AI__FALLBACK_MODELS: fast-model
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"